### ISSUE TITLE
Wikipedia API Call example

### ISSUE THREAD

**Issue by njsfield** [FAC9/hapi-places#16]
https://en.wikipedia.org/w/api.php?action=query&prop=extracts&exintro&titles=Madrid&format=json

Replace 'Madrid' with City name.

Note that this returns a JSON object that contains an 'extract' key with nested data,
![image](https://cloud.githubusercontent.com/assets/16468314/20521319/9dabee6e-b0a2-11e6-9283-06b39352f8db.png)

We need a function that can access the extract key each time, it should take the property name ('extract') and the whole data, and return 'extracts value'

**Comment by denesnori** [comment]
Object.values(city.query.pages)[0].extract
where city is the json object return the right data
