### ISSUE TITLE
Function to parse JSON data from Nomadlist function

### ISSUE THREAD

**Issue by njsfield** [FAC9/hapi-places#27]
and return an object like this;

Object props/values

{ cost : '$1234' }
{ temp : '20.0' }
{ internet: 'GOOD' }
{ air : '10%' }
{ coffee : '$' }
{ image : 'urltoimage' }

**Comment by denesnori** [comment]
{image:'img'}

**Comment by denesnori** [comment]
We have so far...
console.log(amsterdam.result[0].media.image['1500']); //pic
console.log(amsterdam.result[0].cost.nomad.USD); //cost
console.log(amsterdam.result[0].info.internet.speed.download); //download speed
console.log(amsterdam.result[0].cost.coffee_in_cafe.USD); //cofee
console.log(amsterdam.result[0].info.weather.temperature.celsius); // temp
console.log(amsterdam.result[0].scores.safety); //safety
console.log(amsterdam.result[0].info.country.name);
