### ISSUE TITLE
crashes if you request a safer place than utrecht

### ISSUE THREAD

**Issue by Jwhiles** [FAC9/hapi-places#39]
Presumably this is because utrecht is ONE HUNDRED PERCENT SAFE and there is NOWHERE SAFER

I was once hassled by some teenagers in Ttrecht.

**Comment by emilyb7** [comment]
Just remembered that we calculate a percentage but nomadlist looks at decimal value from 0 to 1. I think we need to validate all the filters a bit more thoroughly...

**Comment by emilyb7** [comment]
Although if it only crashes on Utrecht, maybe it's not so bad? I'm on the train right now, will check later...

**Comment by emilyb7** [comment]
@Jwhiles i fixed this on our up-and-kicking branch!
