### ISSUE TITLE
Refactor the handlers

### ISSUE THREAD

**Issue by sohilpandya** [FAC9/hapi-places#74]
https://github.com/FAC9/hapi-places/blob/master/src/routes.js#L5-L42

There is a potential to refactor this codebase and split them up into three different handlers which can then be plugged into the route.

**Comment by sohilpandya** [comment]
This can also be said of this file https://github.com/FAC9/hapi-places/blob/master/src/request.js#L2-L89

You have the potential to putting each individual function in its own file under a `lib` folder.

**Comment by sohilpandya** [comment]
Guess what? You could probably do with refactoring this as well - https://github.com/FAC9/hapi-places/blob/master/test/backend_test.js#L1-L132

Just think of how easy you'll make it for everyone when all your tests are in an individual file. ❤️

**Comment by denesnori** [comment]
hups, I forgot to link it, but pull request #104 refactors the tests.
