### ISSUE TITLE
Request.js

### ISSUE THREAD

**Issue by tbtommyb** [FAC9/hapi-places#85]
What is the point of this bit on line 50?

`else if (JSON.parse(body).query.pages[-1])`

Accessing the -1 index returns undefined in JavaScript.

**Comment by njsfield** [comment]
-1 is actually a key in the JSON data returned. The function checks to see if this key exists, it is a key which is unique to a null-data JSON response. 
This is returned when a faulty api call is made to wikipedia;
![image](https://cloud.githubusercontent.com/assets/16468314/20571474/7a7804d4-b19f-11e6-9dc0-8692c280deb7.png)
